name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake
  - cudatoolkit=11.8
  - cudnn=8.1
  - cxx-compiler
  - jupyterlab
  - mpi4py # installs cuda-aware openmpi
  - nccl
  - nvcc_linux-64=11.8
  - openmpi
  - pip
  - pip:
    - tensorflow-gpu==2.8.*
    - -r horovod.txt
  - python=3.8
