name: null

channels:
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake=3.22
  - cudatoolkit=11.2
  - cudnn=8.1
  - cxx-compiler
  - mpi4py # installs cuda-aware openmpi
  - nccl
  - nvcc_linux-64=11.2
  - openmpi
  - pip
  - pip:
    - tensorflow-gpu==2.8.*
    - -r distributed.txt
  - pytest
  - python=3.8
