name: horovod-gpu

channels:
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake=3.22
  - cudatoolkit=11.2
  - cudnn=8.1
  - cxx-compiler
  - mpi4py
  - nccl
  - nvcc_linux-64=11.2
  - openmpi
  - pip
  - pip:
      - tensorflow-gpu==2.8.*
  - python=3.8
