name: horovod-cpu

channels:
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake=3.22
  - cxx-compiler
  - mpi4py # installs cuda-aware openmpi
  - openmpi
  - pip
  - pip:
      - tensorflow-cpu==2.8.*
      - -r base.txt
      - -r dev.txt
  - python=3.8
