name: changed-backends

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    changed-backends:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython
      - name: Get changed backends
        run: python ci/get_changed_backends.py > changed_backends.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: changed-backends
          path: changed_backends.txt
  