name: branches

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  require-base-branch:
    uses: NVIDIA-Merlin/.github/.github/workflows/check-base-branch.yml@main
