name: datasets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements/dev.txt'
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
      - name: Install Merlin dependencies
        run: |
          ref_type=${{ github.ref_type }}
          branch=main
          if [[ $ref_type == "tag"* ]]
          then
            raw=$(git branch -r --contains ${{ github.ref_name }})
            branch=${raw/origin\/}
          fi
          pip install "pandas>=1.2.0,<1.4.0dev0"
          pip install "NVTabular@git+https://github.com/NVIDIA-Merlin/NVTabular.git@$branch"
          pip install "merlin-core@git+https://github.com/NVIDIA-Merlin/core.git@$branch"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Build
        run: |
          python setup.py develop
      - name: Run unittests
        run: |
          make tests-datasets