name: horovod (cpu)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
      - name: Install and upgrade python packages
        run: |
          python -m pip install --upgrade pip setuptools==59.4.0 wheel tox
      - name: Run tests
        run: |
          ref_type=${{ github.ref_type }}
          branch=main
          if [[ $ref_type == "tag"* ]]
          then
            raw=$(git branch -r --contains ${{ github.ref_name }})
            branch=${raw/origin\/}
          fi
          cd ${{ github.workspace }}; tox -e py38-horovod-cpu -- $branch
