name: lightfm

on:
  workflow_run:
    workflows: ["changed-backends"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: changed-backends
      - name: Check if backend changed
        id: check
        run: echo "name=$(grep -q 'lightfm' changed_backends.txt && echo true || echo false)" >> $GITHUB_OUTPUT
    outputs:
      needs_testing: ${{ steps.check.outputs.check }}
  
  tests:
    needs: check
    if: ${{needs.check.outputs.needs_testing == 'true'}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]    

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: changed-backends
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements/dev.txt'
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
      - name: Get Branch name
        id: get-branch-name
        uses: NVIDIA-Merlin/.github/actions/branch-name@main
      - name: Install Merlin dependencies
        run: |
          branch="${{ steps.get-branch-name.outputs.branch }}"
          pip install "NVTabular@git+https://github.com/NVIDIA-Merlin/NVTabular.git@$branch"
          pip install "merlin-core@git+https://github.com/NVIDIA-Merlin/core.git@$branch"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .[lightfm-dev]
      - name: Build
        run: |
          python setup.py develop
      - name: Run unittests
        run: |
          make tests-lightfm-changed