name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install black Jupyter
        run : |
          pip install black[jupyter]==22.3.0
      - uses: pre-commit/action@v2.0.3
