name: release-drafter

on:
  push:
    tags:
      - v*
    release:
      - release*

  workflow_dispatch:

jobs:
  update_release_draft:
    uses: nvidia-merlin/.github/.github/workflows/release-drafter-common.yaml@main