name: release-drafter

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "release*"

  workflow_dispatch:

jobs:
  update_release_draft:
    uses: nvidia-merlin/.github/.github/workflows/release-drafter-common.yaml@main
